steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE', '-f', '$_DOCKERFILE', '.']
images:
  - '$_IMAGE'
substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/mitrufely/mifrufely-repo/comisaria-ms04:latest'
  _DOCKERFILE: 'services/ms-04-guias-contenido/Dockerfile'
options:
  logging: CLOUD_LOGGING_ONLY
