[pytest]
pythonpath = .
asyncio_mode = auto
addopts = -p no:cacheprovider
testpaths = packages/shared/tests services/ms-01-gateway-auth/tests services/ms-02-denuncias-anonimas/tests services/ms-03-reportes-ciudadanos/tests services/ms-04-guias-contenido/tests
